[package]
name = "fetcher"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "tiingo_iex"
path = "src/bin/tiingo_iex.rs"

[[bin]]
name = "fmp_news"
path = "src/bin/fmp_news.rs"

[dependencies]
lambda_runtime = "0.14.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures = "0.3"

serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
parquet = "57.1.0"
arrow = "57.1.0"

aws-config = { version = "1.1", features = ["behavior-version-latest"] }
aws-sdk-dynamodb = "1.11"
aws-sdk-s3 = "1.116.0"

reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }

time = { version = "0.3", features = ["formatting", "parsing"] }
chrono = "0.4"
chrono-tz = "0.10"

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

anyhow = "1.0"

rand = "0.9.2"